/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainform;

import functionality.GetSetInformation;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ihorg
 */
public class SettingsFormJFrame extends javax.swing.JFrame {

    //VARIABLES
    private static Connection conn;
    private static Statement stmt;
    private static ResultSet rs;
    private static String appThemeStr;
    private static Integer appTheme;
    private static Integer appLanguage;
    private static Integer appTextSize;
    private static Integer appTextType;
    private static Integer appTextFont;
    
    
    /**
     * Creates new form SettingsFormJFrame
     */
    public SettingsFormJFrame() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);        
        setDataOnFields();
        setInterfaceSettings(); 
    }
    
    private void setDataOnFields() {
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/dvdb","Halyn","123");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from settings");
            if(rs.next()) {
                if(Integer.parseInt(rs.getString("theme"))==0){
                    jRadioButton1.setSelected(true);
                } else {
                    jRadioButton2.setSelected(true);
                }
                jComboBox1.setSelectedIndex(Integer.parseInt(rs.getString("language")));
                jComboBox2.setSelectedIndex(Integer.parseInt(rs.getString("text_size")));
                jComboBox3.setSelectedIndex(Integer.parseInt(rs.getString("text_type")));
                jComboBox4.setSelectedIndex(Integer.parseInt(rs.getString("text_font")));
            }   
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Налаштування");

        jLabel1.setText("Змінити тему додатку");

        jLabel2.setText("Змінити мову додатку");

        jLabel3.setText("Змінити розмір тексту");

        jLabel4.setText("Змінити тип тектсу");

        jLabel5.setText("Змінити шрифт тексту");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Світла тема");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Темна тема");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Українська", "English" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Маленький", "Середній", "Великий" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Звичайний", "Жирний", "Курсив" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahoma", "Times New Roman", "Arial", "Calibri" }));

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/save.png"))); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/cancel.png"))); // NOI18N
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //THEME
        jRadioButton1.setActionCommand("0");
        jRadioButton2.setActionCommand("1");
        appThemeStr = buttonGroup1.getSelection().getActionCommand();
        if(appThemeStr.equals("0") || appThemeStr.equals("0")) {
            appTheme = 0;
        } else {
            appTheme = 1;
        }
        //LANGUAGE
        appLanguage = jComboBox1.getSelectedIndex();
        //TEXT SIZE
        appTextSize = jComboBox2.getSelectedIndex();
        //TEXT TYPE
        appTextType = jComboBox3.getSelectedIndex();
        //TEXT FONT
        appTextFont = jComboBox4.getSelectedIndex();
        try {
            String s = "update settings set theme="+appTheme+",language="+appLanguage+", text_size="+appTextSize+", text_type="+appTextType+", text_font="+appTextFont+" where id=1";
            System.out.print(s);
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/dvdb","Halyn","123");
            stmt = conn.createStatement(); 
            stmt.executeUpdate(s);
            String allSettings = "select * from settings";
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/dvdb","Halyn","123");
            stmt = conn.createStatement();
            rs = stmt.executeQuery(allSettings);
            if(rs.next()){
                GetSetInformation.setAppTheme(Integer.parseInt(rs.getString("theme")));
                GetSetInformation.setAppLanguage(Integer.parseInt(rs.getString("language")));
                GetSetInformation.setAppTextSize(Integer.parseInt(rs.getString("text_size")));
                GetSetInformation.setAppTextType(Integer.parseInt(rs.getString("text_type")));
                GetSetInformation.setAppTextFont(Integer.parseInt(rs.getString("text_font")));
            }
            setInterfaceSettings();
            setDataOnFields();
        } catch (SQLException ex) {
            Logger.getLogger(SettingsFormJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsFormJFrame().setVisible(true);
            }
        });
    }
    
    private void setInterfaceSettings() {
            getContentPane().setBackground(GetSetInformation.getFormBackground());
            jRadioButton1.setBackground(GetSetInformation.getElementBackground());
            jRadioButton2.setBackground(GetSetInformation.getElementBackground());
            jComboBox1.setBackground(GetSetInformation.getElementBackground());
            jComboBox2.setBackground(GetSetInformation.getElementBackground());
            jComboBox3.setBackground(GetSetInformation.getElementBackground());
            jComboBox4.setBackground(GetSetInformation.getElementBackground());
            jLabel1.setForeground(GetSetInformation.getForeGround());
            jLabel2.setForeground(GetSetInformation.getForeGround());
            jLabel3.setForeground(GetSetInformation.getForeGround());
            jLabel4.setForeground(GetSetInformation.getForeGround());
            jLabel5.setForeground(GetSetInformation.getForeGround());
            jRadioButton1.setForeground(GetSetInformation.getForeGround());
            jRadioButton2.setForeground(GetSetInformation.getForeGround());
            jComboBox1.setForeground(GetSetInformation.getForeGround());
            jComboBox2.setForeground(GetSetInformation.getForeGround());
            jComboBox3.setForeground(GetSetInformation.getForeGround());
            jComboBox4.setForeground(GetSetInformation.getForeGround());
        //LANGUAGE
        if(GetSetInformation.getAppLanguage()==1) {
            String[] combobox2 = {"Small", "Medium", "Big"};
            String[] combobox3 = {"Plain", "Bold", "Italic"};
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(combobox2));
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(combobox3));
            jLabel1.setText("Change app theme");
            jLabel2.setText("Change app language");
            jLabel3.setText("Change app text size");
            jLabel4.setText("Change app text type");
            jLabel5.setText("Change app text font");
            jRadioButton1.setText("Light theme");
            jRadioButton2.setText("Dark theme");
        } else {
            String[] combobox2 = {"Маленький", "Середній", "Великий"};
            String[] combobox3 = {"Звичайний", "Жирний", "Курсив"};
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(combobox2));
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(combobox3));
            jLabel1.setText("Змінити тему додатку");
            jLabel2.setText("Змінити мову додатку");
            jLabel3.setText("Змінити розмір тексту");
            jLabel4.setText("Змінити тип тектсу");
            jLabel5.setText("Змінити шрифт тексту");
            jRadioButton1.setText("Світла тема");
            jRadioButton2.setText("Темна тема");
        }
            jComboBox1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jComboBox2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jComboBox3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jComboBox4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jLabel1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jLabel2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jLabel3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jLabel4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jLabel5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jRadioButton1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
            jRadioButton2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize())); 
            setDataOnFields();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
