/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form3;

import functionality.AddingForm;
import functionality.GetSetInformation;
import java.awt.Font;

/**
 *
 * @author ihorg
 */
public class AddingForm3JFrame extends javax.swing.JFrame {

    //VARIABLES
    private static String s;
    private static AddingForm addingForm;
    private static final String tableName = "personnel";
    
    /**
     * Creates new form AddingForm3JFrame
     */
    public AddingForm3JFrame() {
        initComponents();
        setInterfaceSettings();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addingForm = new AddingForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Додавання запису працівника");

        jLabel9.setText("Телефон");

        jLabel1.setText("№");

        jLabel7.setText("Місто");

        jLabel2.setText("Прізвище");

        jLabel3.setText("Ім'я");

        jLabel8.setText("Дата народження");

        jLabel4.setText("По батькові");

        jLabel10.setText("Пошта");

        jLabel11.setText("Стать");

        jLabel5.setText("Посада");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/add.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Зарплата");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/cancel.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        s = "insert into "+tableName+" values("+jTextField1.getText()+",'"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jTextField7.getText()+"','"+jTextField8.getText()+"','"+jTextField9.getText()+"','"+jTextField10.getText()+"','"+jTextField11.getText()+"',"+(GetSetInformation.getRowCount()+1)+")";
        addingForm.addRecord(s);
        new Form3JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Form3JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingForm3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingForm3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingForm3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingForm3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingForm3JFrame().setVisible(true);
            }
        });
    }
    
    private void setInterfaceSettings() {
        //THEME
        getContentPane().setBackground(GetSetInformation.getFormBackground());
        jTextField1.setBackground(GetSetInformation.getElementBackground());
        jTextField2.setBackground(GetSetInformation.getElementBackground());
        jTextField3.setBackground(GetSetInformation.getElementBackground());
        jTextField4.setBackground(GetSetInformation.getElementBackground());
        jTextField5.setBackground(GetSetInformation.getElementBackground());
        jTextField6.setBackground(GetSetInformation.getElementBackground());
        jTextField7.setBackground(GetSetInformation.getElementBackground());
        jTextField8.setBackground(GetSetInformation.getElementBackground());
        jTextField9.setBackground(GetSetInformation.getElementBackground());
        jTextField10.setBackground(GetSetInformation.getElementBackground());
        jTextField11.setBackground(GetSetInformation.getElementBackground());
        jTextField1.setForeground(GetSetInformation.getForeGround());
        jTextField2.setForeground(GetSetInformation.getForeGround());
        jTextField3.setForeground(GetSetInformation.getForeGround());
        jTextField4.setForeground(GetSetInformation.getForeGround());
        jTextField5.setForeground(GetSetInformation.getForeGround());
        jTextField6.setForeground(GetSetInformation.getForeGround());
        jTextField7.setForeground(GetSetInformation.getForeGround());
        jTextField8.setForeground(GetSetInformation.getForeGround());
        jTextField9.setForeground(GetSetInformation.getForeGround());
        jTextField10.setForeground(GetSetInformation.getForeGround());
        jTextField11.setForeground(GetSetInformation.getForeGround());
        jLabel1.setForeground(GetSetInformation.getForeGround());
        jLabel2.setForeground(GetSetInformation.getForeGround());
        jLabel3.setForeground(GetSetInformation.getForeGround());
        jLabel4.setForeground(GetSetInformation.getForeGround());
        jLabel5.setForeground(GetSetInformation.getForeGround());
        jLabel6.setForeground(GetSetInformation.getForeGround());
        jLabel7.setForeground(GetSetInformation.getForeGround());
        jLabel8.setForeground(GetSetInformation.getForeGround());
        jLabel9.setForeground(GetSetInformation.getForeGround());
        jLabel10.setForeground(GetSetInformation.getForeGround());
        jLabel11.setForeground(GetSetInformation.getForeGround());
        //LANGUAGE
        if(GetSetInformation.getAppLanguage()==1) {
            jLabel1.setText("#");
            jLabel2.setText("Surname");
            jLabel3.setText("Name");
            jLabel4.setText("Mid name");
            jLabel5.setText("Position");
            jLabel6.setText("Salary");
            jLabel7.setText("City");
            jLabel8.setText("Birht date");
            jLabel9.setText("Phone");
            jLabel10.setText("Email");
            jLabel11.setText("Gender");
        }
        //TEXT
        jLabel1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel6.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel7.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel8.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel9.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel10.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel11.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField6.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField7.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField8.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField9.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField10.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField11.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
