/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form4;

import functionality.AddingForm;
import functionality.GetSetInformation;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ihorg
 */
public class EditingForm4JFrame extends javax.swing.JFrame {

    //VARIABLES
    private static Connection conn;
    private static Statement stmt;
    private static ResultSet rs;
    private static String[][] tableDataArr;
    private static Integer currentRow,currentId;
    private final JFileChooser openFileChooser;
    private final JFileChooser saveFileChooser;
    private BufferedImage originalBI;
    private static AddingForm addingForm;
    private static final String openFilePath = "C:\\Users\\ihorg\\Documents\\NetBeansProjects\\DVDB\\src\\images\\photodb\\drugs";
    private static final String saveFilePath = "C:\\Users\\ihorg\\Documents\\NetBeansProjects\\DVDB\\src\\images\\product photos";
    private static final String host = "smtp.gmail.com";
    private static final String sender = "ihorgalyn452@gmail.com";
    private static final String password = "vamga2003";
    private static String recipient = "";
    private static final String subject = "Замовлення змінено!";
    private static String text = "";
    private static final String image = "C:\\Users\\ihorg\\Documents\\NetBeansProjects\\DVDB\\src\\images\\product photos\\pf"+(GetSetInformation.getRowCount())+".png";
    private static final String tableName = "orders";
    
    /**
     * Creates new form EditingForm4JFrame
     */
    public EditingForm4JFrame() {
        initComponents();
        setInterfaceSettings();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tableDataArr = new String[GetSetInformation.getRowCount()][GetSetInformation.getColCount()];
        currentRow = GetSetInformation.getCurrentRow();
        currentId = GetSetInformation.getCurrentId();
        DataPreparing();
        setDataOnTextFields();    
        addingForm = new AddingForm();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File(openFilePath));
        saveFileChooser = new JFileChooser();
        saveFileChooser.setCurrentDirectory(new File(saveFilePath));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        resultButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalPriceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        currencyLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        openFileButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        saveFileButton = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Редагувати замовлення");

        prev.setText("<");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        next.setText(">");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/save.png"))); // NOI18N
        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/cancel.png"))); // NOI18N
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel6.setText("Кількість");

        resultButton.setText("Підсумкова ціна");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Продавець");

        jLabel3.setText("Пошта");

        currencyLabel.setText("грн");

        jLabel4.setText("Товар");

        openFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/open.png"))); // NOI18N
        openFileButton.setContentAreaFilled(false);
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Виберіть фото");

        saveFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/save.png"))); // NOI18N
        saveFileButton.setContentAreaFilled(false);
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Ціна");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalPriceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultButton)
                            .addComponent(totalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currencyLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //DATA PREPARING
    private void DataPreparing() {
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/dvdb","Halyn","123");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from "+tableName);
            while(rs.next()) {
                for(int j = 0;j<GetSetInformation.getColCount();j++){
                    tableDataArr[rs.getRow()-1][j] = rs.getString(j+1);
                }
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    //SETS DATA ON TEXTFIELDS
    private void setDataOnTextFields() {
        jTextField2.setText(tableDataArr[currentRow][1]);
        jTextField3.setText(tableDataArr[currentRow][2]);
        jTextField4.setText(tableDataArr[currentRow][3]);
        jTextField5.setText(tableDataArr[currentRow][4]);
        jTextField6.setText(tableDataArr[currentRow][5]);
        totalPriceTextField.setText(tableDataArr[currentRow][6]);
    }
    
    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        if (currentRow == 0){
            currentRow = GetSetInformation.getRowCount()-1;
            currentId = Integer.parseInt(tableDataArr[currentRow][0]);
        }
        else {
            currentRow-=1;
            currentId = Integer.parseInt(tableDataArr[currentRow][0]);
        }
        setDataOnTextFields();
    }//GEN-LAST:event_prevActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (currentRow == GetSetInformation.getRowCount()-1){
            currentRow = 0;
            currentId = Integer.parseInt(tableDataArr[currentRow][0]);
        }
        else {
            currentRow+=1;
            currentId = Integer.parseInt(tableDataArr[currentRow][0]);
        }
        setDataOnTextFields();
    }//GEN-LAST:event_nextActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            if(!totalPriceTextField.getText().equals("")) {
                stmt = conn.createStatement();
                String s = "update "+tableName+" set seller ='"+jTextField2.getText()+"',email='"+jTextField3.getText()+"',product='"+jTextField4.getText()+"',price="+jTextField5.getText()+",count="+jTextField6.getText()+",total_price="+totalPriceTextField.getText()+" where act_id ="+currentId+"";
                stmt.executeUpdate(s);
                text = "Замовлення №"+(GetSetInformation.getRowCount())+" змінено!\nПокупець: Медичний центр \"ДВ\"\nАдреса: Львів, вул. Петра Дорошенка 65\nТовар: "+jTextField4.getText()+"\nЦіна: "+jTextField5.getText()+"\nКількість: "+jTextField6.getText()+"\nПідсумкова ціна: "+totalPriceTextField.getText()+"\nФото: ";
                recipient = jTextField3.getText();
                addingForm.sendMessageToEmail(host, sender, password, recipient, subject, text, image);
            }else {
                if(GetSetInformation.getAppLanguage()==0) {
                    messageLabel.setText("Підсумкова кількість не вирахувана!");
                } else {
                    messageLabel.setText("The final amount is not calculated!");
                }
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(EditingForm4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new Form4JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        totalPriceTextField.setText(""+(Integer.parseInt(jTextField5.getText())*Integer.parseInt(jTextField6.getText())));
    }//GEN-LAST:event_resultButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                originalBI = ImageIO.read(openFileChooser.getSelectedFile());
                if(GetSetInformation.getAppLanguage()==0) {
                    messageLabel.setText("Файл успішно завантажено!");
                } else {
                    messageLabel.setText("Підсумкова кількість не вирахувана!");
                }
            } catch (IOException ex) {
                if(GetSetInformation.getAppLanguage()==0) {
                    messageLabel.setText("Файл не вдалося завантажити");
                } else {
                    messageLabel.setText("The file could not be downloaded");
                }
            }
        } else {
            if(GetSetInformation.getAppLanguage()==0) {
                messageLabel.setText("Файл не вибраний");
            } else {
                messageLabel.setText("File not selected");
            }
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        int returnValue = saveFileChooser.showSaveDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIO.write(originalBI, "png", saveFileChooser.getSelectedFile());
                if(GetSetInformation.getAppLanguage()==0) {
                    messageLabel.setText("Файл успішно збережено!");
                } else {
                    messageLabel.setText("File saved successfully!");
                }
            } catch (IOException ex) {
                if(GetSetInformation.getAppLanguage()==0) {
                    messageLabel.setText("Файл не вдалося зберегти");
                } else {
                    messageLabel.setText("Failed to save file");
                }
            }
        } else {
            if(GetSetInformation.getAppLanguage()==0) {
                messageLabel.setText("Файл не вибраний");
            } else {
                messageLabel.setText("File not selected");
            }
        }
    }//GEN-LAST:event_saveFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditingForm4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditingForm4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditingForm4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditingForm4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditingForm4JFrame().setVisible(true);
            }
        });
    }
    
    private void setInterfaceSettings() {
        //THEME
        getContentPane().setBackground(GetSetInformation.getFormBackground());
        jTextField2.setBackground(GetSetInformation.getElementBackground());
        jTextField3.setBackground(GetSetInformation.getElementBackground());
        jTextField4.setBackground(GetSetInformation.getElementBackground());
        jTextField5.setBackground(GetSetInformation.getElementBackground());
        jTextField6.setBackground(GetSetInformation.getElementBackground());
        totalPriceTextField.setBackground(GetSetInformation.getElementBackground());
        prev.setBackground(GetSetInformation.getElementBackground());
        next.setBackground(GetSetInformation.getElementBackground());
        resultButton.setForeground(GetSetInformation.getElementBackground());
        jTextField2.setForeground(GetSetInformation.getForeGround());
        jTextField3.setForeground(GetSetInformation.getForeGround());
        jTextField4.setForeground(GetSetInformation.getForeGround());
        jTextField5.setForeground(GetSetInformation.getForeGround());
        jTextField6.setForeground(GetSetInformation.getForeGround());
        totalPriceTextField.setForeground(GetSetInformation.getForeGround());
        jLabel2.setForeground(GetSetInformation.getForeGround());
        jLabel3.setForeground(GetSetInformation.getForeGround());
        jLabel4.setForeground(GetSetInformation.getForeGround());
        jLabel5.setForeground(GetSetInformation.getForeGround());
        jLabel6.setForeground(GetSetInformation.getForeGround());
        messageLabel.setForeground(GetSetInformation.getElementBackground());
        currencyLabel.setForeground(GetSetInformation.getElementBackground());
        prev.setForeground(GetSetInformation.getElementBackground());
        next.setForeground(GetSetInformation.getElementBackground());
        resultButton.setForeground(GetSetInformation.getElementBackground());
        //LANGUAGE
        if(GetSetInformation.getAppLanguage()==1) {
            jLabel2.setText("Seller");
            jLabel3.setText("Email");
            jLabel4.setText("Product");
            jLabel5.setText("Price");
            jLabel6.setText("Count");
            resultButton.setText("Total price");
            messageLabel.setText("Chose picture");
            currencyLabel.setText("uah");
        }
        //TEXT
        jLabel2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel6.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        resultButton.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        messageLabel.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        currencyLabel.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField6.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton next;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton prev;
    private javax.swing.JButton resultButton;
    private javax.swing.JButton save;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JTextField totalPriceTextField;
    // End of variables declaration//GEN-END:variables
}
