/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form4;

import functionality.AddingForm;
import functionality.Form;
import functionality.GetSetInformation;
import functionality.PhotoViewerFormJFrame;
import java.awt.Font;


/**
 *
 * @author ihorg
 */
public class Form4JFrame extends javax.swing.JFrame {
    
    //VARIABLES
    private static final String firstParam = "seller",secParam="product",thirdParam="total_price"; 
    private static Form form;
    private static final String singleFilterStr="count";
    private static AddingForm addingForm;
    private static String[] headersNames = {"№","Продавець","Пошта","Товар","Ціна", "Кількість", "Підсумкова ціна"};
    private static final String imageDirectory = "product photos";
    private static final String imageType = "\\pf";
    private static final String host = "smtp.gmail.com";
    private static final String sender = "ihorgalyn452@gmail.com";
    private static final String password = "vamga2003";
    private static String recipient = "";
    private static final String subject = "Відміна замовлення";
    private static String text = "";
    private static final String image = GetSetInformation.generalPath+"\\photodb\\reject.png";
    private static final String tableName = "orders";
    private static final String searchStr = "id";
    
    /**
     * Creates new form Form4JFrame
     */
    public Form4JFrame() {
        initComponents();
        setInterfaceSettings();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if(GetSetInformation.getAppLanguage() == 1) {
            headersNames = new String[]{"#","Seller","Email","Product","Price", "Count", "Total price"};
        }
        form = new Form(jTable1,tableName,headersNames);
        form.userAccessSettings(addButton, editButton, deleteButton);
        form.displayTable();
        addingForm = new AddingForm();
        GetSetInformation.setRowCount(jTable1.getRowCount());
        GetSetInformation.setColCount(jTable1.getColumnCount());
        form.refreshTable();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        home = new javax.swing.JButton();
        first = new javax.swing.JButton();
        search = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        tripleFilterBtn = new javax.swing.JButton();
        next = new javax.swing.JButton();
        refreshTable = new javax.swing.JButton();
        last = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        singleFilterTF = new javax.swing.JTextField();
        singleFilterBtn = new javax.swing.JButton();
        photoViewerButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Замовлення");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/add.png"))); // NOI18N
        addButton.setContentAreaFilled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/delete.png"))); // NOI18N
        deleteButton.setContentAreaFilled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/home.png"))); // NOI18N
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        first.setText("<<");
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/search.png"))); // NOI18N
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        prev.setText("<");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        tripleFilterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/filter.png"))); // NOI18N
        tripleFilterBtn.setContentAreaFilled(false);
        tripleFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripleFilterBtnActionPerformed(evt);
            }
        });

        next.setText(">");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        refreshTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/refresh.png"))); // NOI18N
        refreshTable.setContentAreaFilled(false);
        refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableActionPerformed(evt);
            }
        });

        last.setText(">>");
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });

        jLabel1.setText("№");

        jLabel3.setText("Продавець");

        jLabel4.setText("Товар");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Ціна");

        jLabel2.setText("Кількість >");

        jLabel6.setText("шт");

        singleFilterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/filter.png"))); // NOI18N
        singleFilterBtn.setContentAreaFilled(false);
        singleFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleFilterBtnActionPerformed(evt);
            }
        });

        photoViewerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/image.png"))); // NOI18N
        photoViewerButton.setContentAreaFilled(false);
        photoViewerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoViewerButtonActionPerformed(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photodb/edit.png"))); // NOI18N
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleFilterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(photoViewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tripleFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(singleFilterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(refreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoViewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tripleFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //ADD
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        form.addingFormOpening();
        new AddingForm4JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_addButtonActionPerformed

   //DELETE
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        form.deleteImage(imageDirectory, imageType);
        form.deleteRecord();
        text = "Замовлення №"+(GetSetInformation.getRowCount())+" відмінено!";
        recipient = "alexsokirka452@gmail.com";
        addingForm.sendMessageToEmail(host, sender, password, recipient, subject, text, image);
    }//GEN-LAST:event_deleteButtonActionPerformed
    //HOME
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        dispose();
    }//GEN-LAST:event_homeActionPerformed
    //FIRST RECORD
    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        form.firstRecord();
    }//GEN-LAST:event_firstActionPerformed
    //SEARCH
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        form.search(jTextField1, searchStr);
    }//GEN-LAST:event_searchActionPerformed
    //PREV RECORD
    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        form.prevRecord();
    }//GEN-LAST:event_prevActionPerformed
    //TRIPLE FILTER
    private void tripleFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripleFilterBtnActionPerformed
        form.tripleFilter(firstParam, secParam, thirdParam, jTextField1, jTextField2, jTextField3);
    }//GEN-LAST:event_tripleFilterBtnActionPerformed
    //NEXT
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        form.nextRecord();
    }//GEN-LAST:event_nextActionPerformed
    //REFRESH TABLE
    private void refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableActionPerformed
        form.refreshTable();
    }//GEN-LAST:event_refreshTableActionPerformed
    //LAST
    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        form.lastRecord();
    }//GEN-LAST:event_lastActionPerformed
    //SALARY > QUANTITY
    private void singleFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleFilterBtnActionPerformed
        form.singleFilter(singleFilterTF, singleFilterStr);
    }//GEN-LAST:event_singleFilterBtnActionPerformed

    private void photoViewerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoViewerButtonActionPerformed
        form.photoViewerFormOpening();
        new PhotoViewerFormJFrame().setVisible(true);
    }//GEN-LAST:event_photoViewerButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        form.editingFormOpening();
        new EditingForm4JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form4JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form4JFrame().setVisible(true);
            }
        });
    }
    
    private void setInterfaceSettings() {
        //THEME
        getContentPane().setBackground(GetSetInformation.getFormBackground());
        jTable1.setBackground(GetSetInformation.getElementBackground());
        first.setBackground(GetSetInformation.getElementBackground());
        prev.setBackground(GetSetInformation.getElementBackground());
        next.setBackground(GetSetInformation.getElementBackground());
        last.setBackground(GetSetInformation.getElementBackground());
        searchTF.setBackground(GetSetInformation.getElementBackground());
        jTextField1.setBackground(GetSetInformation.getElementBackground());
        jTextField2.setBackground(GetSetInformation.getElementBackground());
        jTextField3.setBackground(GetSetInformation.getElementBackground());
        first.setForeground(GetSetInformation.getForeGround());
        prev.setForeground(GetSetInformation.getForeGround());
        next.setForeground(GetSetInformation.getForeGround());
        last.setForeground(GetSetInformation.getForeGround());
        jLabel1.setForeground(GetSetInformation.getForeGround());
        jLabel2.setForeground(GetSetInformation.getForeGround());
        jLabel3.setForeground(GetSetInformation.getForeGround());
        jLabel4.setForeground(GetSetInformation.getForeGround());
        jLabel5.setForeground(GetSetInformation.getForeGround());
        jLabel6.setForeground(GetSetInformation.getForeGround());
        searchTF.setForeground(GetSetInformation.getForeGround());
        singleFilterTF.setForeground(GetSetInformation.getForeGround());
        jTextField1.setForeground(GetSetInformation.getForeGround());
        jTextField2.setForeground(GetSetInformation.getForeGround());
        jTextField3.setForeground(GetSetInformation.getForeGround());   
        //LANGUAGE
        if(GetSetInformation.getAppLanguage()==1) {
            jLabel1.setText("#");
            jLabel2.setText("Count >");
            jLabel3.setText("Seller");
            jLabel4.setText("Product");
            jLabel5.setText("Price");
            jLabel6.setText("pc");
        }
        //TEXT
        jLabel1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel4.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel5.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jLabel6.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        singleFilterTF.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        searchTF.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField1.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField2.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
        jTextField3.setFont(new Font(GetSetInformation.getTextFont(), GetSetInformation.getTextType(), GetSetInformation.getTextSize()));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton first;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton last;
    private javax.swing.JButton next;
    private javax.swing.JButton photoViewerButton;
    private javax.swing.JButton prev;
    private javax.swing.JButton refreshTable;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton singleFilterBtn;
    private javax.swing.JTextField singleFilterTF;
    private javax.swing.JButton tripleFilterBtn;
    // End of variables declaration//GEN-END:variables
}
